In [5]:
df= "Hi Iam Thaneesh"

In [6]:
df.split()

['Hi', 'Iam', 'Thaneesh']

In [7]:
planet = "Mars"
diameter = 13743

In [8]:
print('The diameter of {} is {} kilometer .'.format(planet,diameter));

The diameter of Mars is 13743 kilometer .


In [9]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [11]:
d['k1'][3]['tricky'][3]['target'][3]

'hello'

In [12]:
import numpy as np

In [13]:
s = np.zeros(12)
s

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [15]:
v= np.ones(10)*6
v

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [18]:
a = np.arange(20,35,2)
a

array([20, 22, 24, 26, 28, 30, 32, 34])

In [19]:
array = np.arange(0,9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
a=np.array([1,2,3])
b=np.array([4,5,6])
np.concatenate((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

In [21]:
import pandas as pd

In [27]:
d = {"names":["Thaneesh","SEnbagaraman","Parthiban"],"Age":[21,21,21]}
df = pd.DataFrame(d)
df

names  Age
0      Thaneesh   21
1  SEnbagaraman   21
2     Parthiban   21

In [28]:
p =pd.date_range(start='1-2-2022',end='30-3-2022')
for val in p:
  print(val)


2022-01-02 00:00:00
2022-01-03 00:00:00
2022-01-04 00:00:00
2022-01-05 00:00:00
2022-01-06 00:00:00
2022-01-07 00:00:00
2022-01-08 00:00:00
2022-01-09 00:00:00
2022-01-10 00:00:00
2022-01-11 00:00:00
2022-01-12 00:00:00
2022-01-13 00:00:00
2022-01-14 00:00:00
2022-01-15 00:00:00
2022-01-16 00:00:00
2022-01-17 00:00:00
2022-01-18 00:00:00
2022-01-19 00:00:00
2022-01-20 00:00:00
2022-01-21 00:00:00
2022-01-22 00:00:00
2022-01-23 00:00:00
2022-01-24 00:00:00
2022-01-25 00:00:00
2022-01-26 00:00:00
2022-01-27 00:00:00
2022-01-28 00:00:00
2022-01-29 00:00:00
2022-01-30 00:00:00
2022-01-31 00:00:00
2022-02-01 00:00:00
2022-02-02 00:00:00
2022-02-03 00:00:00
2022-02-04 00:00:00
2022-02-05 00:00:00
2022-02-06 00:00:00
2022-02-07 00:00:00
2022-02-08 00:00:00
2022-02-09 00:00:00
2022-02-10 00:00:00
2022-02-11 00:00:00
2022-02-12 00:00:00
2022-02-13 00:00:00
2022-02-14 00:00:00
2022-02-15 00:00:00
2022-02-16 00:00:00
2022-02-17 00:00:00
2022-02-18 00:00:00
2022-02-19 00:00:00
2022-02-20 00:00:00


In [32]:
lists =[[1,'Stk',22],[2,'Sen',22],[3,'Par',22]]

In [31]:
df = pd.DataFrame(lists)
df

0    1   2
0  1  stk  22
1  2  sen  22
2  3  par  22