# 1.**Split** **this** **String**

In [1]:
data="I am Senbagaraman"

In [2]:
data.split()

['I', 'am', 'Senbagaraman']

# 2. **Use** .**format**(**bold text**) **to** **print** **the** **following** **string**.

In [3]:
plant="mars"
diameter=12888

In [4]:
print('The diameter of {} is {} kilometer.'.format(plant,diameter))

The diameter of mars is 12888 kilometer.


# **3. In** **this** **nest** **dictionary** **grab** **the** **word** "**hello**"

In [5]:
a={'k1':[1,2,3,{'tricky':['Oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
a['k1'][3]['tricky'][3]['target'][3]

'hello'


# **Numpy**

In [7]:
import numpy as np

# 4.1 **Create** **an** **array** **of** **10** **zeros**?

# 4.2 **Create:** **an** **array** **of** **10** **fives**?

In [8]:
b=np.zeros(10)
b

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
c=np.ones(10)*5
c

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. **Create an array of all the even integers from 20 to 35**

In [12]:
d=np.arange(20,35,2)
d

array([20, 22, 24, 26, 28, 30, 32, 34])

# **6. Create a 3x3 matrix with values ranging from 0 to 8**

In [13]:
array=np.arange(0,9).reshape(3,3)
array

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

# **7. Concatenate e and f**


In [14]:
e=np.array([1,2,3])
f=np.array([4,5,6])
np.concatenate((e,f),axis=0)

array([1, 2, 3, 4, 5, 6])

# **8.Pandas**

In [15]:
import pandas as pd
d={"names":["senbagaraman","thaneesh","parthiban"],"Age":[21,21,21]}
data=pd.DataFrame(d)
data

names  Age
0  senbagaraman   21
1      thaneesh   21
2     parthiban   21


# **9. Generate the series of dates from 1st Jan, 2022 to 30th Jan, 2022**

In [18]:
p=pd.date_range(start='1-1-2022',end='30-1-2022')
for val in p:
  print(val)

2022-01-01 00:00:00
2022-01-02 00:00:00
2022-01-03 00:00:00
2022-01-04 00:00:00
2022-01-05 00:00:00
2022-01-06 00:00:00
2022-01-07 00:00:00
2022-01-08 00:00:00
2022-01-09 00:00:00
2022-01-10 00:00:00
2022-01-11 00:00:00
2022-01-12 00:00:00
2022-01-13 00:00:00
2022-01-14 00:00:00
2022-01-15 00:00:00
2022-01-16 00:00:00
2022-01-17 00:00:00
2022-01-18 00:00:00
2022-01-19 00:00:00
2022-01-20 00:00:00
2022-01-21 00:00:00
2022-01-22 00:00:00
2022-01-23 00:00:00
2022-01-24 00:00:00
2022-01-25 00:00:00
2022-01-26 00:00:00
2022-01-27 00:00:00
2022-01-28 00:00:00
2022-01-29 00:00:00
2022-01-30 00:00:00


# **10. Create 2D list to DataFrame**

In [19]:
list=[[1,'a',22],[2,'b',22],[3,'c',22]]

In [20]:
data=pd.DataFrame(list)
data

0  1   2
0  1  a  22
1  2  b  22
2  3  c  22